<?php
/**
 * SuiteCRM main configuration file.
 * Generated for the Docker-based CANALI development environment.
 * DB host matches the 'db' service defined in docker-compose.yml.
 */
$sugar_config = array(
    'dbconfig' => array(
        'db_host_name'     => 'db',
        'db_host_instance' => 'SQLEXPRESS',
        'db_user_name'     => 'suitecrm',
        'db_password'      => 'suitecrm',
        'db_name'          => 'suitecrm',
        'db_type'          => 'mysql',
        'db_port'          => '',
        'db_manager'       => 'MysqliManager',
    ),
    'dbconfigoption' => array(
        'persistent' => true,
        'autofree'   => false,
        'debug'      => 0,
        'ssl'        => false,
    ),
    'site_url'                => 'http://18.136.195.116:8080',
    'host_name'               => '18.136.195.116',
    'http_referer'            => array(
        'list' => array('18.136.195.116'),
    ),
    'unique_key'              => 'canali_suite_crm_2024',
    'cache_dir'               => 'cache/',
    'upload_dir'              => 'upload/',
    'session_dir'             => '',
    'log_dir'                 => '.',
    'log_level'               => 'fatal',
    'installer_locked'        => true,
    'language'                => 'en_us',
    'default_language'        => 'en_us',
    'default_charset'         => 'UTF-8',
    'default_theme'           => 'SuiteP',
    'default_currency_name'   => 'US Dollars',
    'default_currency_symbol' => '$',
    'default_currency_iso4217'=> 'USD',
    'default_locale_name_format' => 's f l',
    'default_date_format'     => 'm/d/Y',
    'default_time_format'     => 'h:ia',
    'default_decimal_seperator'        => '.',
    'default_number_grouping_seperator'=> ',',
    'default_email_charset'   => 'UTF-8',
    'default_export_charset'  => 'UTF-8',
    'export_delimiter'        => ',',
    'disable_export'          => false,
    'default_max_tabs'        => 7,
    'list_max_entries_per_page' => 20,
    'list_max_entries_per_subpanel' => 10,
    'translation_string_prefix' => false,
    'js_lang_version'         => 1,
    'email_warning_notifications' => '',
    'require_accounts'        => false,
    'disable_count_query'     => false,
    'hide_subpanels'          => false,
    'hide_subpanels_on_login' => false,
    'subpanelTabs'            => true,
    'lock_homepage'           => false,
    'use_real_names'          => false,
    'stack_trace_errors'      => false,
    'disableAjaxUI'           => false,
    'js_available'            => 1,
    'js_custom_version'       => '',
    'tracker_max_display_length' => 30,
    'quicksearch_querydelay'  => 500,
    'email_default_client'    => 'sugar',
    'email_xss'               => true,
    'email_sugarclient_listviewmaxselect' => 1000,
    'allow_sendmail_outbound' => true,
    'allow_pop_inbound'       => true,
    'disabled_languages'      => '',
    'languages'               => array('en_us' => 'English (US)'),
    'time_formats'            => array('h:ia' => '12:00am', 'H:i' => '23:00'),
    'image_ext'               => array('.jpg', '.jpeg', '.png', '.gif'),
    'valid_image_ext'         => array('.jpg', '.jpeg', '.png', '.gif'),
    'id_validation_pattern'   => '/^[0-9a-f\-]+$/i',
    'security_trusted_domains'    => array(),
    'securitysuite_filter_user_list' => false,
    'web_to_lead_allowed_redirect_hosts' => array(),
    'addAjaxBannedModules'    => array(),
    'overrideAjaxBannedModules' => array(),
    'custom_help_url'         => '',
    'custom_help_base_url'    => '',
    'resource_management' => array(
        'default_limit'    => 20000,
        'special_query_limit' => 50000,
        'special_query_modules' => array(),
    ),
    'cron' => array(
        'allowed_cron_users' => array('www-data'),
    ),
    'aos' => array(
        'lineItems' => array(
            'enableGroups' => 0,
            'totalTax'     => 0,
        ),
        'contracts' => array(
            'renewalReminderPeriod' => 30,
        ),
    ),
    'enable_themes'           => '1',
    'sugarbeet'               => true,
    'hide_backtrace'          => false,
    'sugar_version'           => '7.12.5',
    'sugar_flavor'            => 'CE',
    'passwordsetting' => array(
        'SystemGeneratedPasswordEnable'   => false,
        'generatepasswordtmpl'            => '',
        'lostpasswordtmpl'                => '',
        'minpwdlength'                    => '6',
        'maxpwdlength'                    => '',
        'oneupper'                        => false,
        'onelower'                        => false,
        'onenumber'                       => false,
        'onespecial'                      => false,
        'UserMustChangePasswordOnFirstLogin' => false,
    ),
    'logger' => array(
        'level'        => 'fatal',
        'file'         => 'suitecrm.log',
        'default_log'  => 'suitecrm',
        'type'         => 'SugarLogger',
    ),
);
